[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "autohooks"
version = "26.9.1.dev1"
description = "Library for managing git hooks"
authors = [{ name = "Greenbone AG", email = "info@greenbone.net" }]
requires-python = ">=3.10,<4"
readme = "README.md"
license = "GPL-3.0-or-later"
keywords = ["git", "formatting", "linting", "hooks"]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
  "Environment :: Console",
  "Intended Audience :: Developers",
  "Intended Audience :: System Administrators",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Operating System :: OS Independent",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Topic :: Software Development :: Version Control :: Git",
  "Programming Language :: Python :: 3",
]
dependencies = [
  "tomlkit>=0.5.11",
  "pontos>=22.8.0",
  "rich>=12.5.1",
  "shtab>=1.7.0",
  "typing-extensions>=4.16.0,<5",
]

[project.urls]
Homepage = "https://github.com/greenbone/autohooks/"
Repository = "https://github.com/greenbone/autohooks/"
Documentation = "https://greenbone.github.io/autohooks/"

[project.scripts]
autohooks = "autohooks.cli:main"

[dependency-groups]
dev = [
  "autohooks-plugin-ruff>=23.6.0",
  "autohooks-plugin-mypy>=23.3.0",
  "coverage>=7.2.7",
  "rope>=1.9.0",
  "Sphinx>=5.3.0",
  "furo>=2023.3.27",
  "myst-parser>=1.0.0",
  "sphinx-tabs>=3.4.0",
  "mypy>=0.991",
]

[tool.uv]
default-groups = "all"

[tool.autohooks]
pre-commit = [
  'autohooks.plugins.mypy',
  'autohooks.plugins.ruff.check',
  'autohooks.plugins.ruff.format',
]
mode = "uv"

[tool.pontos.version]
version-module-file = "autohooks/__version__.py"

[tool.mypy]
files = "autohooks"
ignore_missing_imports = true
explicit_package_bases = true

[tool.coverage.run]
omit = ["tests/*", "*/__init__.py"]
source = ["autohooks"]

[tool.ruff]
line-length = 80
target-version = "py310"
extend-select = ["I", "PLE", "PLW"]

[tool.hatch.build.targets.wheel]
packages = ["autohooks"]
include = ["autohooks/precommit/template"]

[tool.hatch.build.targets.sdist]
include = [
  "autohooks",
  "docs",
  "tests",
  "uv.lock",
  "autohooks/precommit/template",
  "autohooks.gif",
]
